' indicators_registry.bas - GENERE AUTOMATIQUEMENT
' Ne pas modifier manuellement.

Extern "C"
    Declare Sub Register_ADR112 Alias "Register_ADR112" (reg As Any Ptr)
    Declare Sub Register_AnchoredVWAP Alias "Register_AnchoredVWAP" (reg As Any Ptr)
    Declare Sub Register_ATRChannel Alias "Register_ATRChannel" (reg As Any Ptr)
    Declare Sub Register_BBHL Alias "Register_BBHL" (reg As Any Ptr)
    Declare Sub Register_BollingerBands Alias "Register_BollingerBands" (reg As Any Ptr)
    Declare Sub Register_CoronaTrendVigor Alias "Register_CoronaTrendVigor" (reg As Any Ptr)
    Declare Sub Register_CyAn1Fty Alias "Register_CyAn1Fty" (reg As Any Ptr)
    Declare Sub Register_DirectionalVolumeIndex Alias "Register_DirectionalVolumeIndex" (reg As Any Ptr)
    Declare Sub Register_DVIValueChart Alias "Register_DVIValueChart" (reg As Any Ptr)
    Declare Sub Register_Ichimoku Alias "Register_Ichimoku" (reg As Any Ptr)
    Declare Sub Register_MAFiboEnv Alias "Register_MAFiboEnv" (reg As Any Ptr)
    Declare Sub Register_YearlyPivot Alias "Register_YearlyPivot" (reg As Any Ptr)
    Declare Sub Register_MovingAverage Alias "Register_MovingAverage" (reg As Any Ptr)
    Declare Sub Register_MurreyMath Alias "Register_MurreyMath" (reg As Any Ptr)
    Declare Sub Register_RealMACD Alias "Register_RealMACD" (reg As Any Ptr)
    Declare Sub Register_RSI Alias "Register_RSI" (reg As Any Ptr)
    Declare Sub Register_SharpeRatio Alias "Register_SharpeRatio" (reg As Any Ptr)
    Declare Sub Register_Stochastic Alias "Register_Stochastic" (reg As Any Ptr)
    Declare Sub Register_StochasticRSI Alias "Register_StochasticRSI" (reg As Any Ptr)
    Declare Sub Register_SwamiRSI Alias "Register_SwamiRSI" (reg As Any Ptr)
    Declare Sub Register_TMACG Alias "Register_TMACG" (reg As Any Ptr)
    Declare Sub Register_TSCD Alias "Register_TSCD" (reg As Any Ptr)
    Declare Sub Register_TSF Alias "Register_TSF" (reg As Any Ptr)
    Declare Sub Register_VolatilityPivot Alias "Register_VolatilityPivot" (reg As Any Ptr)
    Declare Sub Register_WeeklyPivot Alias "Register_WeeklyPivot" (reg As Any Ptr)
    Declare Sub Register_WeightedWCCI Alias "Register_WeightedWCCI" (reg As Any Ptr)
End Extern

Sub RegisterAllIndicators(reg As Any Ptr)
    Register_ADR112(reg)
    Register_AnchoredVWAP(reg)
    Register_ATRChannel(reg)
    Register_BBHL(reg)
    Register_BollingerBands(reg)
    Register_CoronaTrendVigor(reg)
    Register_CyAn1Fty(reg)
    Register_DirectionalVolumeIndex(reg)
    Register_DVIValueChart(reg)
    Register_Ichimoku(reg)
    Register_MAFiboEnv(reg)
    Register_YearlyPivot(reg)
    Register_MovingAverage(reg)
    Register_MurreyMath(reg)
    Register_RealMACD(reg)
    Register_RSI(reg)
    Register_SharpeRatio(reg)
    Register_Stochastic(reg)
    Register_StochasticRSI(reg)
    Register_SwamiRSI(reg)
    Register_TMACG(reg)
    Register_TSCD(reg)
    Register_TSF(reg)
    Register_VolatilityPivot(reg)
    Register_WeeklyPivot(reg)
    Register_WeightedWCCI(reg)
End Sub
